### ISSUE TITLE
Changes to implement before migration to ecmwf-lab

### ISSUE THREAD

**Issue by cvitolo** [wikilimo/ml-fuel#1]
Hello @roshni-b  and @lazyoracle!

The repository can be transferred to ecmwf-lab. Before doing that we will need to implement the changes listed below in order to consistent with other projects hosted at [ecmwf-lab](https://github.com/ecmwf-lab).

I tried to address points 1-5 below in the PR, however these need to be checked for consistency.
There is one outstanding issue (point 6 below) with regards to the automatic testing using GitHub actions/workflows. Is this something you could help with? Many thanks!

[From Florian]
It would be great if your repos could have :
1. The name and contact information of the author(s) and the best way to contact you. Interested users may send an email to you or post a question in the "issues" in the correct category with a descriptive tag if you enable the github issue tracker.
2. Add a link to the doc in the README (https://ml-fuel.readthedocs.io/en/latest/intro.html).
3. Renaming demo-notebooks/ as notebooks/ ?
4. Mixing CamelCase and underscore in the notebook names ?  Could CatBoost_inference.ipynb be cat_boost_inference.ipynb ?
5. Run black one your code : we promote using "black" (https://github.com/psf/black) to have a consistent formatting across all code in ecmwf-lab.
6. Automatic testing : Using .github/workflows for continuous integration tests is the recommended standard, with pytest. Ideally, your repos should have this also. I am not sure how much you can test without actually training the model, but ensuring that ‘pip install’ runs ok is possible. And perhaps running a dummy training and dummy inference step to make sure the tools you are using works. Perhaps a simplified version of this https://github.com/ecmwf/climetlab/blob/master/.github/workflows/check-and-publish.yml

**Comment by lazyoracle** [comment]
>1. The name and contact information of the author(s) and the best way to contact you. Interested users may send an email to you or post a question in the "issues" in the correct category with a descriptive tag if you enable the github issue tracker.

Done.

>2. Add a link to the doc in the README (https://ml-fuel.readthedocs.io/en/latest/intro.html).

Done
 
>3. Renaming demo-notebooks/ as notebooks/ ?

Done

>4. Mixing CamelCase and underscore in the notebook names ?  Could CatBoost_inference.ipynb be cat_boost_inference.ipynb ?

It is the name of an existing, established GBDT model and that is the way the authors spell it, so we are sticking with it.
 
>5. Run black one your code : we promote using "black" (https://github.com/psf/black) to have a consistent formatting across all code in ecmwf-lab.

Included in the pre-commit configs and now also part of the CI checks.

 
>6. Automatic testing : Using .github/workflows for continuous integration tests is the recommended standard, with pytest. Ideally, your repos should have this also. I am not sure how much you can test without actually training the model, but ensuring that ‘pip install’ runs ok is possible. And perhaps running a dummy training and dummy inference step to make sure the tools you are using works. Perhaps a simplified version of this https://github.com/ecmwf/climetlab/blob/master/.github/workflows/check-and-publish.yml

Done.
